export const basecamp = {
  id: "bacharach",
  name: "Bacharach Basecamp",
  region: "UNESCO Upper Middle Rhine Valley",
  bookingUrl: "https://www.bacchus-holiday-homes.com/unterkuenfte/verfuegbarkeit-and-buchen/",
};

export const surfaces = [
  {
    id: "explorer",
    label: "Mittelrhein Explorer",
    purpose: "Regional knowledge",
    url: "https://www.bacchus-holiday-homes.com/mittelrhein-explorer/",
  },
  {
    id: "live-guide",
    label: "Mittelrhein Live Guide",
    purpose: "Mobile day guidance",
    url: "https://www.bacchus-holiday-homes.com/mittelrhein-explorer/mittelrhein-live-guide/",
  },
  {
    id: "map",
    label: "Mittelrhein Map",
    purpose: "Spatial orientation",
    url: "https://www.bacchus-holiday-homes.com/mittelrhein-explorer/mittelrhein-karte/",
  },
  {
    id: "concierge",
    label: "Middle Rhine AI Concierge",
    purpose: "Personal planning",
    url: "https://www.bacchus-holiday-homes.com/ai-concierge/",
  },
  {
    id: "stay",
    label: "Direct booking",
    purpose: "Conversion",
    url: basecamp.bookingUrl,
  },
];

export const places = [
  {
    id: "bacharach-old-town",
    name: "Bacharach Old Town",
    location: "Bacharach",
    category: "heritage",
    themes: ["history", "architecture", "photography", "slow"],
    modes: ["walk"],
    duration: 90,
    familyScore: 4,
    indoorScore: 1,
    source: "explorer",
    action: "Open walking orientation",
  },
  {
    id: "stahleck-view",
    name: "Burg Stahleck viewpoint",
    location: "Bacharach",
    category: "castle",
    themes: ["castles", "views", "history", "hiking"],
    modes: ["walk"],
    duration: 75,
    familyScore: 3,
    indoorScore: 1,
    source: "map",
    action: "Open route from Basecamp",
  },
  {
    id: "werner-chapel",
    name: "Werner Chapel",
    location: "Bacharach",
    category: "heritage",
    themes: ["history", "architecture", "photography"],
    modes: ["walk"],
    duration: 35,
    familyScore: 3,
    indoorScore: 1,
    source: "explorer",
    action: "Open heritage context",
  },
  {
    id: "rhine-promenade",
    name: "Rhine promenade",
    location: "Bacharach",
    category: "nature",
    themes: ["river", "slow", "family", "photography"],
    modes: ["walk"],
    duration: 50,
    familyScore: 5,
    indoorScore: 1,
    source: "live-guide",
    action: "Open nearby route",
  },
  {
    id: "oberwesel-city-museum",
    name: "Oberwesel City Museum",
    location: "Oberwesel",
    category: "culture",
    themes: ["culture", "rain", "family", "slow"],
    modes: ["train"],
    duration: 90,
    familyScore: 4,
    indoorScore: 5,
    source: "live-guide",
    action: "Verify today’s museum opening status",
    volatile: true,
  },
  {
    id: "oberwesel-walls",
    name: "Oberwesel town walls",
    location: "Oberwesel",
    category: "heritage",
    themes: ["history", "views", "walking", "photography"],
    modes: ["train", "car"],
    duration: 120,
    familyScore: 3,
    indoorScore: 1,
    source: "map",
    action: "Open rail-connected day route",
  },
  {
    id: "kaub-pfalzgrafenstein",
    name: "Kaub & Pfalzgrafenstein view",
    location: "Kaub",
    category: "castle",
    themes: ["castles", "river", "history", "photography"],
    modes: ["train", "boat", "car"],
    duration: 120,
    familyScore: 4,
    indoorScore: 2,
    source: "map",
    action: "Open rail and river options",
    volatile: true,
  },
  {
    id: "rheinfels",
    name: "Rheinfels Castle experience",
    location: "St. Goar",
    category: "castle",
    themes: ["castles", "history", "family", "views"],
    modes: ["train", "car"],
    duration: 150,
    familyScore: 5,
    indoorScore: 3,
    source: "explorer",
    action: "Verify access and opening status",
    volatile: true,
  },
  {
    id: "loreley",
    name: "Loreley plateau",
    location: "St. Goarshausen",
    category: "viewpoint",
    themes: ["views", "river", "myth", "photography"],
    modes: ["train", "boat", "car"],
    duration: 150,
    familyScore: 4,
    indoorScore: 1,
    source: "map",
    action: "Build cross-river route",
    volatile: true,
  },
  {
    id: "rhine-castle-trail",
    name: "RheinBurgenWeg stage",
    location: "From Bacharach",
    category: "hike",
    themes: ["hiking", "views", "active", "nature"],
    modes: ["walk", "train"],
    duration: 240,
    familyScore: 2,
    indoorScore: 0,
    source: "explorer",
    action: "Open six-day hiking logic",
    volatile: true,
  },
  {
    id: "rhine-cruise",
    name: "Castle corridor by boat",
    location: "Middle Rhine",
    category: "river",
    themes: ["river", "castles", "slow", "photography"],
    modes: ["boat", "walk"],
    duration: 180,
    familyScore: 5,
    indoorScore: 3,
    source: "explorer",
    action: "Verify today’s timetable",
    volatile: true,
  },
  {
    id: "riesling-evening",
    name: "Bacharach Riesling evening",
    location: "Bacharach",
    category: "wine",
    themes: ["wine", "food", "local", "slow"],
    modes: ["walk"],
    duration: 120,
    familyScore: 1,
    indoorScore: 5,
    source: "live-guide",
    action: "Open local partner options",
    volatile: true,
  },
  {
    id: "boppard-bend",
    name: "Boppard Rhine bend",
    location: "Boppard",
    category: "viewpoint",
    themes: ["views", "river", "hiking", "photography"],
    modes: ["train", "car"],
    duration: 210,
    familyScore: 3,
    indoorScore: 1,
    source: "map",
    action: "Open regional connection",
  },
  {
    id: "koblenz-confluence",
    name: "Rhine–Moselle confluence",
    location: "Koblenz",
    category: "city",
    themes: ["city", "history", "river", "family"],
    modes: ["train", "car"],
    duration: 210,
    familyScore: 4,
    indoorScore: 2,
    source: "map",
    action: "Open regional rail route",
  },
];

export function surfaceById(id) {
  return surfaces.find((surface) => surface.id === id) || surfaces[0];
}
